= fxx
:jfx: javafx
:fxx: io.vulpine.lib.fxx

Builder style extensions for JavaFX classes.

[source,java]
----
var tab = new Tab("title");
tab.setStyle("-fx-something: value");
tab.getStyleClass().addAll("tabby", "some-class");
tab.setOnClose(myCloseHandler);

myTabPane.getTabs().add(tab);
----

vs

[source,java]
----
myTabPane.add(
  new Tab("title")
    .style("-fx-something: value")
    .styleClasses("tabby", "some-class")
    .onClose(myCloseHandler)
);
----

== Progress

Until v1 is reached this listing will track what is presently implemented.
Once v1 is reached this library should mirror all the major control/pane types
present in JavaFX.

[%header, width="25%", cols=3]
.Implementation Mapping
|===
^|Since  ^|JavaFX                           ^| Mirror
^|v0.0.6 >|`{jfx}.scene.control.Accordion`  <|`{fxx}.control.Accordion`
^|v0.0.7 >|`{jfx}.scene.control.Alert`      <|`{fxx}.control.Alert`
^|v0.0.6 >|`{jfx}.scene.control.Button`     <|`{fxx}.control.Button`
^|v0.0.7 >|`{jfx}.scene.control.ButtonBar`  <|`{fxx}.control.ButtonBar`
^|v0.0.6 >|`{jfx}.scene.control.CheckBox`   <|`{fxx}.control.CheckBox`
^|v0.0.7 >|`{jfx}.scene.control.Dialog`     <|`{fxx}.control.Dialog`
^|v0.0.5 >|`{jfx}.scene.control.Label`      <|`{fxx}.control.Label`
^|v0.0.7 >|`{jfx}.scene.control.Menu`       <|`{fxx}.menu.Menu`
^|v0.0.7 >|`{jfx}.scene.control.MenuBar`    <|`{fxx}.menu.MenuBar`
^|v0.0.7 >|`{jfx}.scene.control.MenuButton` <|`{fxx}.menu.MenuButton`
^|v0.0.7 >|`{jfx}.scene.control.MenuItem`   <|`{fxx}.menu.MenuItem`
^|v0.0.6 >|`{jfx}.scene.control.ScrollPane` <|`{fxx}.control.ScrollPane`
^|v0.0.1 >|`{jfx}.scene.control.Tab`        <|`{fxx}.control.Tab`
^|v0.0.1 >|`{jfx}.scene.control.TabPane`    <|`{fxx}.control.TabPane`
^|v0.0.6 >|`{jfx}.scene.control.TextArea`   <|`{fxx}.control.TextArea`
^|v0.0.6 >|`{jfx}.scene.control.TextField`  <|`{fxx}.control.TextField`
^|v0.0.6 >|`{jfx}.scene.control.TitledPane` <|`{fxx}.control.TitledPane`
^|v0.0.3 >|`{jfx}.scene.layout.AnchorPane`  <|`{fxx}.layout.AnchorPane`
^|v0.0.4 >|`{jfx}.scene.layout.BorderPane`  <|`{fxx}.layout.BorderPane`
^|v0.0.4 >|`{jfx}.scene.layout.DialogPane`  <|`{fxx}.layout.DialogPane`
^|v0.0.4 >|`{jfx}.scene.layout.FlowPane`    <|`{fxx}.layout.FlowPane`
^|v0.0.3 >|`{jfx}.scene.layout.GridPane`    <|`{fxx}.layout.GridPane`
^|v0.0.2 >|`{jfx}.scene.layout.HBox`        <|`{fxx}.layout.HBox`
^|v0.0.3 >|`{jfx}.scene.layout.Pane`        <|`{fxx}.layout.Pane`
^|v0.0.3 >|`{jfx}.scene.layout.Region`      <|`{fxx}.layout.Region`
^|v0.0.4 >|`{jfx}.scene.layout.StackPane`   <|`{fxx}.layout.StackPane`
^|v0.0.4 >|`{jfx}.scene.layout.TilePane`    <|`{fxx}.layout.TilePane`
^|v0.0.2 >|`{jfx}.scene.layout.VBox`        <|`{fxx}.layout.VBox`
^|v0.0.8 >|`{jfx}.scene.Scene`              <|`{fxx}.scene.Scene`
^|v0.0.8 >|`{jfx}.scene.SubScene`           <|`{fxx}.scene.SubScene`
^|v0.0.5 >|`{jfx}.scene.text.Text`          <|`{fxx}.text.Text`
^|v0.0.7 >|`{jfx}.scene.text.TextFlow`      <|`{fxx}.text.TextFlow`
|===