= fxx

Builder style extensions for JavaFX classes.

[source,java]
----
var tab = new Tab("title");
tab.setStyle("-fx-something: value");
tab.getStyleClass().addAll("tabby", "some-class");
tab.setOnClose(myCloseHandler);

myTabPane.getTabs().add(tab);
----

vs

[source,java]
----
myTabPane.add(
  new Tab("title")
    .style("-fx-something: value")
    .styleClasses("tabby", "some-class")
    .onClose(myCloseHandler)
);
----

== Progress

Until v1 is reached this listing will track what is presently implemented.
Once v1 is reached this library should mirror all the major control/pane types
present in JavaFX.

[%header, width="25%", cols=3]
.Implementation Mapping
|===
^|Since  ^|JavaFX                           ^| Mirror
^|v0.0.6 >|`javafx.scene.control.Accordion`  <|`io.vulpine.lib.fxx.control.Accordion`
^|v0.0.6 >|`javafx.scene.control.Button`     <|`io.vulpine.lib.fxx.control.Button`
^|v0.0.6 >|`javafx.scene.control.CheckBox`   <|`io.vulpine.lib.fxx.control.CheckBox`
^|v0.0.5 >|`javafx.scene.control.Label`      <|`io.vulpine.lib.fxx.control.Label`
^|v0.0.6 >|`javafx.scene.control.ScrollPane` <|`io.vulpine.lib.fxx.control.ScrollPane`
^|v0.0.1 >|`javafx.scene.control.Tab`        <|`io.vulpine.lib.fxx.control.Tab`
^|v0.0.1 >|`javafx.scene.control.TabPane`    <|`io.vulpine.lib.fxx.control.TabPane`
^|v0.0.6 >|`javafx.scene.control.TextArea`   <|`io.vulpine.lib.fxx.control.TextArea`
^|v0.0.6 >|`javafx.scene.control.TextField`  <|`io.vulpine.lib.fxx.control.TextField`
^|v0.0.6 >|`javafx.scene.control.TitledPane` <|`io.vulpine.lib.fxx.control.TitledPane`
^|v0.0.3 >|`javafx.scene.layout.AnchorPane`  <|`io.vulpine.lib.fxx.layout.AnchorPane`
^|v0.0.4 >|`javafx.scene.layout.BorderPane`  <|`io.vulpine.lib.fxx.layout.BorderPane`
^|v0.0.4 >|`javafx.scene.layout.DialogPane`  <|`io.vulpine.lib.fxx.layout.DialogPane`
^|v0.0.4 >|`javafx.scene.layout.FlowPane`    <|`io.vulpine.lib.fxx.layout.FlowPane`
^|v0.0.3 >|`javafx.scene.layout.GridPane`    <|`io.vulpine.lib.fxx.layout.GridPane`
^|v0.0.2 >|`javafx.scene.layout.HBox`        <|`io.vulpine.lib.fxx.layout.HBox`
^|v0.0.3 >|`javafx.scene.layout.Pane`        <|`io.vulpine.lib.fxx.layout.Pane`
^|v0.0.3 >|`javafx.scene.layout.Region`      <|`io.vulpine.lib.fxx.layout.Region`
^|v0.0.4 >|`javafx.scene.layout.StackPane`   <|`io.vulpine.lib.fxx.layout.StackPane`
^|v0.0.4 >|`javafx.scene.layout.TilePane`    <|`io.vulpine.lib.fxx.layout.TilePane`
^|v0.0.2 >|`javafx.scene.layout.VBox`        <|`io.vulpine.lib.fxx.layout.VBox`
^|v0.0.5 >|`javafx.scene.text.Text`          <| io.vulpine.lib.fxx.text.Text`
|===